name: pytorch
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - python=3.6
  - pytorch-cpu=0.4.1
  - scikit-learn
  - pip:
      - black
      - path.py
      - pylint
      - torchtext
      - torchvision
